graphql:
  servlet:
    enabled: true
    mapping: /graphql
    exception-handlers-enabled: true
    websocket:
      enabled: false
  tools:
    schema-location-pattern: "/graphql/*.graphqls"
    introspection-enabled: true
graphiql:
  enabled: true
  mapping: /graphiql
  endpoint:
    graphql: /graphql
logging:
  level:
    graphql.kickstart: DEBUG